#!/bin/sh
lock() {
    i3lock -c 272822 --insidecolor=272822FF --ringcolor=0088CCFF --ringvercolor=272822FF --keyhlcolor=005599FF --bshlcolor=005599FF --textcolor=FFFFFFFF --separatorcolor=272822FF --linecolor=00000000 -k
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
